name: Run TSC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: c-hive/gha-yarn-cache@v2
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1
